### ISSUE TITLE
Schedule Keycloak pods on different nodes

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#621]
### Description

As we don't want a two Keycloak instances fail when a node fails, once could give a hint to Kubernetes to schedule Keycloak pods on different nodes. 

```
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: keycloak
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
```

Given when there are multiple deployments of Keycloak in the cluster (or in that namespace), additional labels should be present to distinguish those.

### Motivation

If a node dies, only one Keycloak instance of that cluster should die to avoid losing entries in the distributed caches.
