### ISSUE TITLE
Use ARM architecture to run Keycloak 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#908]
### Description

OpenShift with hosted control planes now supports ARM workers. Using such workers would be in-line with our company strategy.

### Motivation

Save cloud costs both for us and our users

**Comment by ahus1** [comment]
The following worked succcessfully: 

Create an ARM worker pool:

```
rosa create machinepool -c gh-keycloak-a --instance-type m6g.4xlarge --max-replicas 10 --min-replicas 1 --name scaling-arm --enable-autoscaling --autorepair
```

Add a scheduling to the `keycloak.yaml` to start Keycloak on the ARM workers:

```
  scheduling:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: keycloak
                  app.kubernetes.io/component: server
                  app.kubernetes.io/instance: keycloak
                  app.kubernetes.io/managed-by: keycloak-operator
              topologyKey: topology.kubernetes.io/zone
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: keycloak
                  app.kubernetes.io/component: server
                  app.kubernetes.io/instance: keycloak
                  app.kubernetes.io/managed-by: keycloak-operator
              topologyKey: kubernetes.io/hostname
```

I might have needed to kill a previously running pod. After that Keycloak started on the ARM pod. 

Next steps: 
* See what happens if we only have ARM workers in our cluster. Which services start? Do we then still need the schedule settings for Keycloak?
* We are building the image with the JDBC driver for AWS. How can we build such an image for ARM? Maybe adding a node selector for the build might be required to force the node - if source-to-image supports that. 
   ```
     nodeSelector
       kubernetes.io/arch: arm64
   ```
